#!/usr/bin/env python
import sqlite3
import sys

def get_symbol(raw):
	raw = raw.upper()
        if not "_" in raw:
            raw += "_BTC"
	return raw

def get_symbols(symstr):
	symstr = get_symbol(symstr)
	syms = symstr.split("_")
	if len(syms) != 2:
		print "Shitty symbol provided: '%s' - must be of format CUR1_CUR2 ... BTC_USD for example" % symstr
		sys.exit(1)
	first = syms[0]
	second = syms[1]
        if first == second:
            print "Shitty symbol provided: '%s' - you can't buy a pair cosnsiting of one currency" % symstr
            sys.exit(2)
	return (first, second)



class Transaction(object):
    pair = ""
    action = ""
    amount = 0.0
    price = 0.0


def get_transactions(sym):
    con = sqlite3.connect("db.sqlite")
    con.row_factory = sqlite3.Row
    cur = con.execute("SELECT * FROM transactions where pair = '" + sym + "';")
    txs = []
    for row in cur:
        tx = Transaction()
        tx.pair = row['pair']
        tx.amount = row['amount']
        tx.price = row['price']
        tx.action = row['action']
        txs.append(tx)
    con.close()
    return txs

def avg(sym):
    ts = get_transactions(sym)
    total_price = 0.0
    total_amount = 0.0
    for tx in ts:
        if tx.action == "BUY":
            total_price += (tx.price * tx.amount)
            total_amount += tx.amount
        if tx.action == "SELL":
            total_price -= (tx.price * t.amount)
            total_amount -= tx.amount
    return total_price / total_amount

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "syntax: %s <SYMBOL>" % sys.argv[0]
        print "example: %s SC_BTC"
        sys.exit()

    symbol = get_symbol(sys.argv[1])
    a = avg(symbol)
    print "avg buy price: %4.8f" % a

