#!/usr/bin/env python
import sys
import sqlite3
import urllib, json


def get_symbol(raw):
    raw = raw.upper()
    if not "_" in raw:
        raw += "_BTC"
    return raw

def get_symbols(symstr):
    symstr = get_symbol(symstr)
    syms = symstr.split("_")
    if len(syms) != 2:
        print "Shitty symbol provided: '%s' - must be of format CUR1_CUR2 ... BTC_USD for example" % symstr
        sys.exit(1)
    first = syms[0]
    second = syms[1]
    if first == second:
        print "Shitty symbol provided: '%s' - you can't buy a pair cosnsiting of one currency" % symstr
        sys.exit(2)
    return (first, second)



def bttrex(sym):
    bsym = sym
    if not "-" in sym:
        elms = sym.split("_")
        bsym = elms[1] + "-" + elms[0]
    url = "https://bittrex.com/api/v1.1/public/getticker?market=" + bsym
    response = urllib.urlopen(url)
    data = json.loads(response.read())
    rate = float(data["result"]["Last"])
    return rate

def btc_price(sym):
    return bttrex(sym)

if __name__ == "__main__":
    symbol = "USDT-BTC"
    print "%s: %14.8f" % (symbol, btc_price(symbol))
