#!/usr/bin/env python
import sqlite3
import sys

def get_symbol(raw):
	raw = raw.upper()
	return raw

def get_symbols(symstr):
	symstr = get_symbol(symstr)
	syms = symstr.split("_")
	if len(syms) != 2:
		print "Shitty symbol provided: '%s' - must be of format CUR1_CUR2 ... BTC_USD for example" % symstr
		sys.exit(1)
	first = syms[0]
	second = syms[1]
	return (first, second)

def get_amount(raw):
	return float(raw)

def get_price(raw):
	raw = raw.upper()
	if "S" in raw:
		raw = raw.split("S")[0]
		raw = 0.00000001 * float(raw) 
	return float(raw)

def print_confirmation(symbol, amount, price):
	syms = get_symbols(symbol)
	total = amount * price
	print "Does this sound right?"
	print("BUY %.2f %s @ %.8f %s" % (amount, syms[0], price, syms[1]))
	print("TOTAL: %.8f %s" % (total, syms[1]))

if len(sys.argv) != 4:
	print "syntax: buy <amount> <symbol> <price>"
	print "example: buy 100 BTC_USD 1800"
	print sys.argv
	sys.exit()

symbol = get_symbol(sys.argv[2])
amount = get_amount(sys.argv[1])
price = get_price(sys.argv[3])

print_confirmation(symbol, amount, price)
